CREATE TABLE ORDER(
    ORDER_ID SERIAL,
    ACCOUNT_ID INT,
    SYMBOL VARCHAR(256),
    AMOUNT INT,
    PRICE FLOAT,
    STATE ENUM('open', 'execute', 'cancel'),
    TIME TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
)