CREATE TABLE ACCOUNT(
    ACCOUNT_ID INT,
    BALANCE FLOAT,
    PRIMARY KEY (ACCOUNT_ID)
)

CREATE TABLE STOCK(
    STOCK_ID SERIAL,
    ACCOUNT_ID INT,
    SYMBOL VARCHAR(256),
    AMOUNT INT,
    PRIMARY KEY (STOCK_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE ORDER(
    ORDER_ID SERIAL,
    ACCOUNT_ID INT,
    SYMBOL VARCHAR(256),
    AMOUNT INT,
    PRICE FLOAT,
    STATE ENUM('open', 'execute', 'cancel'),
    TIME TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
)