CREATE TABLE STOCK(
    STOCK_ID SERIAL,
    ACCOUNT_ID INT,
    SYMBOL VARCHAR(256),
    AMOUNT INT,
    PRIMARY KEY (ACCOUNT_ID, SYMBOL),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

